# permissions for end users to view krakends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: krakend-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krakend-operator
    app.kubernetes.io/part-of: krakend-operator
    app.kubernetes.io/managed-by: kustomize
  name: krakend-viewer-role
rules:
- apiGroups:
  - gateway.krakend.io
  resources:
  - krakends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.krakend.io
  resources:
  - krakends/status
  verbs:
  - get
