apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: krakend-sample-service
                port:
                  number: 8080